# Generated by Django 3.2.16 on 2023-06-23 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('anime_type', models.CharField(choices=[('tv', 'TV series'), ('movie', 'Movie')], max_length=5)),
                ('name_en', models.CharField(max_length=100)),
                ('name_ru', models.CharField(max_length=100)),
                ('name_jp', models.CharField(max_length=100, null=True)),
                ('anime_id', models.IntegerField(primary_key=True, serialize=False)),
                ('scr_exist', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ScreenshotsInAnime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField()),
                ('img_path', models.CharField(max_length=4000)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='AnimeQuiz.anime')),
            ],
        ),
        migrations.AddConstraint(
            model_name='screenshotsinanime',
            constraint=models.UniqueConstraint(fields=('anime', 'order_number'), name='SIA_anime_number_uk'),
        ),
    ]
